taskmanager/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.views.static import serve
from .decorators import isAuthenticated, isAdmin
from .views import *

# applications url patterns
urlpatterns = [
    path('', isAuthenticated(IssueListView.as_view()), name='issue'),
    path('issue/add/', isAdmin(IssueAddView.as_view()), name='issue-add'),
    path('issue/delete/<int:pk>/', isAdmin(issueDelete), name='issue-delete'),
    path('issue/<int:pk>/', isAdmin(IssueUpdateView.as_view()), name='issue-update'),

    path('user/', isAuthenticated(UserListView.as_view()), name='user'),
    path('user/add/', isAdmin(UserAddView.as_view()), name='user-add'),
    path('user/delete/<int:pk>/', isAdmin(userDelete), name='user-delete'),
    path('user/<int:pk>/', isAdmin(UserUpdateView.as_view()), name='user-update'),

    path('tag/', isAuthenticated(TagListView.as_view()), name='tag'),
    path('tag/add/', isAdmin(TagAddView.as_view()), name='tag-add'),
    path('tag/delete/<int:pk>/', isAdmin(tagDelete), name='tag-delete'),
    path('tag/<int:pk>/', isAdmin(TagUpdateView.as_view()), name='tag-update'),

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout, name='logout'),
]

taskmanager/models.py
import hashlib
from django.conf import settings
from django.db import models


class User(models.Model):
    '''
    User table. Is not necessery to use auth models (too many tables)
    '''
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=100, blank=True, null=True)
    first_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50, blank=True, null=True)
    company = models.CharField(max_length=50, blank=True, null=True)
    is_superadmin = models.BooleanField(default=False)

    def __str__(self):
        '''
        Return string representation of user
        '''
        if self.company:
            return self.company

        if self.first_name or self.last_name:
            return '%s %s' % (self.first_name, self.last_name)

        return self.username

    __unicode__ = __str__

    @staticmethod
    def hashPassword(password):
        h = hashlib.sha256(password.encode('utf8'))
        h.update(settings.SECRET_KEY.encode('utf8'))
        return h.hexdigest()

    def setPassword(self, password):
        self.password = User.hashPassword(password)

    def authenticate(self, password):
        return self.password == User.hashPassword(password)


class Tag(models.Model):
    '''
    Simple tag of Issue, but may be global tags?..
    '''
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title

    # python2 compatible?
    __unicode__ = __str__


class Issue(models.Model):
    '''
    Specific issue
    '''
    # specify choices enum values
    CH_STATE_OPEN = 1
    CH_STATE_IN_PROGRESS = 2
    CH_STATE_CLOSED = 3

    submitter = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='submitters', blank=True, null=True)
    solver = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='solvers', blank=True, null=True)

    title = models.CharField(max_length=50)
    description = models.TextField()

    # use enum values, can be used with language pack...
    state = models.IntegerField(
        choices=(
            (CH_STATE_OPEN, 'Open'),
            (CH_STATE_IN_PROGRESS, 'In progress'),
            (CH_STATE_CLOSED, 'Closed'),
        ),
        default=CH_STATE_OPEN,
    )

    # other fields...
    created = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)

    finished = models.DateTimeField(blank=True, null=True)
    duration = models.IntegerField(blank=True, null=True)

    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return self.title

    # python2 compatible?
    __unicode__ = __str__

    def save(self, *args, **kwargs):
        '''
        If close set finished atribute, set durations.
        Another method is use pre_save signal...
        '''
        if self.finished is not None and self.duration is None:
            self.duration = (self.finished - self.created).seconds

        return super(Issue, self).save(*args, **kwargs)

taskmanager/templates/taskmanager/issue_add.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    <table class="table table-striped">
        {{ form.as_table }}
    </table>
    <input type="submit" value="Add issue" />
</form>
{% endblock %}

taskmanager/templates/taskmanager/issue_list.html
{% extends "base.html" %}
{% load numbers %}

{% block content %}
    <div class="row">
        <div class="col-10">
            <h3>Stats</h3>
            <table  class="table table-condensed table-striped">
                <tr>
                    <th>Max</th>
                    <th>Min</th>
                    <th>Avg</th>
                    <th>Count</th>
                </tr>

                <tr>
                    <td>{{ stats.duration__max }}s</td>
                    <td>{{ stats.duration__max }}s</td>
                    <td>{{ stats.duration__max }}s</td>
                    <td>{{ object_list.count }}</td>
                </tr>
            </table>

            <h3>Tasks</h3>
            <table class="table table-striped">
                <tr>
                    <th>Title</th>
                    <th>State</th>
                    <th>Created</th>
                    <th>Updated</th>
                    <th>Solved</th>
                    <th>Duration</th>
                    <th>Submitter</th>
                    <th>Finished</th>
                    <th>Tags</th>
                    <th>Delete</th>
                </tr>

            {% for issue in object_list %}
                <tr>
                    <td><a href="{% url 'issue-update' issue.pk %}">{{ issue.title }}</a></td>
                    <td>{{ issue.get_state_display }}</td>
                    <td>{{ issue.created }}</td>
                    <td>{{ issue.last_update }}</td>
                    <td>{{ issue.finished }}</td>
                    <td>{{ issue.duration }}</td>
                    <td><a href="{% url 'user-update' issue.submitter_id %}">{{ issue.submitter }}</a></td>
                    <td><a href="{% url 'user-update' issue.solver_id %}">{{ issue.solver }}</a></td>
                    <td>
                        {% for tag in issue.tags.all %}
                            {{ tag }}
                        {% endfor %}
                    </td>
                    <td>
                        <a href="{% url 'issue-delete' issue.pk %}">Delete</a>
                    </td>
                </tr>
            {% empty %}
                <tr><td colspan="7">No issue yet.</td></tr>
            {% endfor %}
            </table>
        </div>

        <div class="col-2">
            <h3>Simple filters</h3>

            <h4>Filter by atg:</h4>
            <a href="?tag=">All</a><br>

            {% for tag in tags %}
                {% if tag.pk == request.GET.tag|int %}
                    {{ tag }}
                {% else %}
                    <a href="?user={{ request.GET.user }}&amp;tag={{ tag.id }}">{{ tag }}</a>
                {% endif %}
                <br>
            {% endfor %}

            <br />

            <h4>Filter by user:</h4>
            <a href="?user=">All</a><br>

            {% for user in users %}
                {% if user.pk == request.GET.user|int %}
                    {{ user }}
                {% else %}
                    <a href="?user={{ user.pk }}&amp;tag={{ request.GET.tag }}">{{ user }}</a>
                {% endif %}
                <br>
            {% endfor %}
        </div>
    </div>
{% endblock %}

taskmanager/templates/taskmanager/issue_update.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Update issue" />
</form>
{% endblock %}

taskmanager/templates/taskmanager/tag_add.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    <table class="table table-striped">
        {{ form.as_table }}
    </table>
    <input type="submit" value="Add tag" />
</form>
{% endblock %}

taskmanager/templates/taskmanager/tag_list.html
{% extends "base.html" %}

{% block content %}
<table class="table table-striped">
    <tr>
        <th>Title</th>
        <th>Action</th>
    </tr>

{% for tag in object_list %}
    <tr>
        <td><a href="{% url 'tag-update' tag.pk %}">{{ tag }}</a></td>
        <td>
            <a href="{% url 'tag-delete' tag.pk %}">Delete</a>
        </td>
    </tr>
{% empty %}
    <tr><td colspan="6">No tags yet.</td></tr>
{% endfor %}
</table>
{% endblock %}

taskmanager/templates/taskmanager/tag_update.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Update tag" />
</form>
{% endblock %}

taskmanager/templates/taskmanager/user_add.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Add user" />
</form>
{% endblock %}

taskmanager/templates/taskmanager/user_list.html
{% extends "base.html" %}

{% block content %}
<table class="table table-striped">
    <tr>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Company</th>
        <th>Superadmin?</th>
        <th>Action</th>
    </tr>

{% for user in object_list %}
    <tr>
        <td><a href="{% url 'user-update' user.pk %}">{{ user.username }}</a></td>
        <td>{{ user.first_name|default_if_none:"Unknown" }}</td>
        <td>{{ user.last_name|default_if_none:"Unknown" }}</td>
        <td>{{ user.company|default_if_none:"Unknown" }}</td>
        <td>{{ user.is_superadmin|yesno }}</td>
        <td>
            <a href="{% url 'user-delete' user.pk %}">Delete</a>
        </td>
    </tr>
{% empty %}
    <tr><td colspan="6">No users yet.</td></tr>
{% endfor %}
</table>
{% endblock %}

taskmanager/templates/taskmanager/user_update.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Update user" />
</form>
{% endblock %}